NetSweet/netsuite

lib/netsuite.rb, lib/netsuite/records/address.rb, lib/netsuite/records/customer_addressbook.rb, lib/netsuite/records/customer_addressbook_list.rb, lib/netsuite/records/location.rb, lib/netsuite/records/sales_order.rb, lib/netsuite/support/sublist.rb, spec/netsuite/records/address_spec.rb, spec/netsuite/records/customer_addressbook_list_spec.rb, spec/netsuite/records/customer_addressbook_spec.rb, spec/netsuite/records/customer_spec.rb
For 2015_1 address record support
Pulling from #210
=> WIP Address record

lib/netsuite.rb, lib/netsuite/actions/get_deleted.rb, lib/netsuite/records/credit_memo.rb, lib/netsuite/records/invoice.rb, lib/netsuite/records/item_receipt.rb, lib/netsuite/support/actions.rb, spec/netsuite/actions/get_deleted_spec.rb, spec/support/fixtures/get_deleted/get_deleted_invoices.xml
The documentation on this is pretty light, so this was assembled by
using the WSDL directly as reference.
=> Add getDeleted Action

lib/netsuite/core_ext/string/lower_camelcase.rb
caml case transformation has been faulty
=> tax_1_amt has been translated to tax_1Amt

lib/netsuite.rb, lib/netsuite/records/customer_deposit.rb, lib/netsuite/records/customer_deposit_apply.rb, lib/netsuite/records/customer_deposit_apply_list.rb
@iloveitaly: This should be pretty straightforward.
=> Add support for CustomerDeposit apply list records

lib/netsuite/records/inventory_adjustment_inventory.rb
* Should be a record_ref, not a field
=> Update InventoryAdjustmentInventory location

lib/netsuite/records/task.rb
I have custom fields on my task, I need this to access and manipulate those fields. I just copied the code from NetSuite::Record::Contact.
=> Expose custom_field_list on NetSuite::Record::Task

lib/netsuite/records/task.rb
Add interface for default field priority - wish I had gotten this in the last request :)
=> Expose priority on NetSuite::Records::Task

lib/netsuite/records/employee.rb
http://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_1/schema/record/employee.html
=> Add altName attribute to employees

lib/netsuite/records/inventory_adjustment_inventory.rb
I added class to InventoryAdjustmentInventory in #340. This PR also adds department to that record type.
=> Add department to inventory adjustment item

README.md, lib/netsuite.rb, lib/netsuite/records/price_level.rb, spec/netsuite/records/price_level_spec.rb
This adds support for the SuiteTalk PriceLevel record.  http://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_1/schema/record/pricelevel.html
=> Add NetSuite::Records::PriceLevel and wsdl_domain documentation

lib/netsuite/records/return_authorization_item.rb, spec/netsuite/records/return_authorization_item_spec.rb
[Reference to the docs](http://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_1/schema/other/returnauthorizationitem.html?mode=package)
=> Add order_line field to ReturnAuthorizationItem record

lib/netsuite.rb, lib/netsuite/actions/update_list.rb, lib/netsuite/records/classification.rb, lib/netsuite/records/inventory_item.rb, lib/netsuite/support/actions.rb, spec/netsuite/actions/update_list_spec.rb, spec/netsuite/records/inventory_item_spec.rb, spec/support/fixtures/update_list/update_list_items.xml, spec/support/fixtures/update_list/update_list_one_item.xml, spec/support/fixtures/update_list/update_list_with_errors.xml
Based on UpsertList by greggroth
=> Added UpdateList Action and parent field to Classifications 

lib/netsuite/records/inbound_shipment.rb
added support for update_list for Inbound Shipments
=> Adding update_list to inbound_shipment

lib/netsuite/errors.rb
=> Type Error

lib/netsuite/records/custom_record.rb
Adding field to custom_record.rb that was not present yet.
=> Add alt_name to custom_record.rb

lib/netsuite/records/assembly_item.rb
Add search_joins to assembly items
=> Add search_joins to assembly items

lib/netsuite/records/vendor_credit.rb, spec/netsuite/records/vendor_credit_spec.rb
Regarding: https://github.com/NetSweet/netsuite/issues/418
=> Adding external_id field to VendorCredit

lib/netsuite/utilities.rb
https://thoughtbot.com/blog/rescue-standarderror-not-exception
=> rescue Exception => rescue StandardError

lib/netsuite/records/service_resale_item.rb, spec/netsuite/records/service_resale_item_spec.rb
I need to grab the `cost` field for part of a project that I am working on.  Sorry this is a very limited PR, but I am trying to push up changes as I make them so they don't get lost.
I also added a spec `ServiceResaleItem` based on the `ServiceSaleItem` spec.  All test are passing on this feature branch.
Let me know of any issues or things that I need to add/change.
=> Add cost to ServiceResaleItem.

lib/netsuite/records/custom_record.rb, spec/netsuite/records/custom_record_spec.rb
Fixes: https://github.com/NetSweet/netsuite/issues/450
Also adds `rec_type` to the `record_refs` tests.
=> Add parent (record_ref) to CustomRecord

lib/netsuite/records/employee.rb, lib/netsuite/records/partner.rb, spec/netsuite/records/employee_spec.rb, spec/netsuite/records/partner_spec.rb
Add `subsidiary` to partner record
Add `sales_role` to employee record
Update tests for employee record
Add tests for partner record
=> Add fields to Partner and Employee records

lib/netsuite/records/contact.rb
My current integration needed these actions for contacts and all seemed to work well using them.
=> Add upsert_list and get_deleted actions for contact record

lib/netsuite.rb, lib/netsuite/records/item_option_custom_field.rb, spec/netsuite/records/item_option_custom_field_spec.rb
Adding class for ItemOptionCustomField
=> add-record-ItemOptionCustomField

lib/netsuite/records/cash_sale.rb
Add upsert list action for cash sales
=> Upsert list action for cash sales

lib/netsuite/records/return_authorization.rb, spec/netsuite/records/return_authorization_spec.rb
Patch to add shipping address to Return authorization, issue https://github.com/NetSweet/netsuite/issues/521
=> Issue-521: Add Ship Address to Return Authorization

lib/netsuite/records/cash_refund_item.rb, spec/netsuite/records/cash_refund_item_spec.rb
Add gross_amt field in cash refund item
=> gross_amt field in cash refund item

lib/netsuite/records/sales_order_item.rb, spec/netsuite/records/sales_order_item_spec.rb
https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2022_1/schema/other/salesorderitem.html
=> Add ship_group attribute to SalesOrderItem

lib/netsuite/records/assembly_item.rb
Add translation list to assembly_item
=> Translation list to assembly_item

lib/netsuite/records/item_fulfillment.rb
=> Add created_from_ship_group field to ItemFulfillment

HISTORY.md
Per @iloveitaly 's request, adding to changelog for change #549
=> Add changelog entry for #549 (thread safety)

netsuite.gemspec
Adding myself as an author to the gemspec at @iloveitaly's request. Appreciate the offer and thanks to the community for all their hard work on this gem. Glad to contribute back wherever I can.
=> Add myself as author

lib/netsuite/records/estimate_item.rb, spec/netsuite/records/estimate_item_spec.rb
Add 3 missing record refs to EstimateItem class:
=> Add department, klass and location EstimateItem/record_refs

lib/netsuite/records/description_item.rb, lib/netsuite/records/subtotal_item.rb
=> fix an incorrect class name

lib/netsuite/records/journal_entry.rb
This action works, so I don't see any reason not to support it.
=> Support update action for journal entries
