NetSweet/netsuite

- lib/netsuite/records/location.rb
Without this, you get an exception when retrieving the results from a
saved search.
> Add missing #search_joins reader/writer

- lib/netsuite/records/custom_field_list.rb
- spec/netsuite/records/custom_field_list_spec.rb
Hi,
I've been working on a netsuite integration and this gem fit like a glove to me. So many thanks for all work that has been put into it.
To make things simpler, I first build a hash with the appropriate keys and sub-hashes, and only then, I initialise a netsuite record to call `#add`.
I realised that a CustomField already takes [`type` or `@xsi:type`](https://github.com/NetSweet/netsuite/blob/master/lib/netsuite/records/custom_field.rb#L13) to initialise.
Since I use CustomFields initialised from within a CustomFieldList, I'd rather use type so my code looks like more idiomatic as opposed to `@xsi:type`. 
I've added a test to make sure the output is as expected.
Let me know if any changes are required.
Cheers
Ricardo
> Allow usage of `type` to instantiate a custom field from a hash

- lib/netsuite/configuration.rb
- spec/netsuite/configuration_spec.rb
Allows configuration of a logger. Useful for using a centralized logger or tagged logging or a logger with multiple backends.
> Add `NetSuite::Configuration#logger=`

- lib/netsuite/records/non_inventory_sale_item.rb
- spec/netsuite/records/non_inventory_sale_item_spec.rb
In the event the external ID needs to be updated for a non-inventory sale item, an update action must be available.
We had this happen in our case and attempted to just use `#upsert`. However, since upserting depends on matching external IDs, we got back error responses.
> Add `#update` action to `NetSuite::Records::NonInventorySaleItem#update`

- lib/netsuite/utilities.rb
- spec/netsuite/utilities_spec.rb
Currently `NetSuite::Utilities#get_record` doesn't cache the results of requests for non-existent records, e.g. for record X when there is no record with id X. But it probably should. These requests will return the same response even if made multiple times.
Check out the spec to reproduce the issue this fixes.
The tests actually pass. CI is failing b/c of a caching issue with Ruby/nokogiri:
> Cache missing record requests

- lib/netsuite/records/item_member.rb
- lib/netsuite/records/member_list.rb
`Support::Records` also implements `to_record`, which overrides the
implementation in `Support::Sublist`.  This causes the items on the
member list to be ommited in the request body.
> Remove errant `include`

- lib/netsuite/records/inventory_transfer_inventory_list.rb
- spec/netsuite/records/inventory_transfer_spec.rb
I observed the `to_record` method leaving off all items from the item list.
> Fix the #to_record method on inventory lists

- lib/netsuite/records/inventory_transfer.rb
```
[1] pry(main)> NetSuite::Records::InventoryTransfer.get(1234)
NoMethodError: undefined method `klass=' for #<NetSuite::Records::InventoryTransfer:0x0055d5407d88e8>
```
> Add missing klass attribute to inventory transfers

- lib/netsuite/records/inventory_adjustment.rb
- lib/netsuite/records/inventory_adjustment_inventory.rb
Element InventoryAdjustment now has a class RecordRef. See https://webservices.netsuite.com/xsd/transactions/v2017_1_0/inventory.xsd on line 24
Without the `:klass` record ref, I get an error when loading an inventory adjustment record with API 2017_1.
> Support class attribute in InventoryAdjustment

- lib/netsuite.rb
- lib/netsuite/records/contact.rb
- lib/netsuite/records/contact_addressbook.rb
- lib/netsuite/records/contact_addressbook_list.rb
- lib/netsuite/records/pricing_matrix.rb
The NetSuite::Records::Contact class includes a reference to CustomerAddressbookList that should be ContactAddressbookList.  This PR fixes this relationship.
> Fix Contact and add ContactAddressbook, ContactAddressbookList classes

- lib/netsuite/records/contact.rb
I believe search_joins should be a part of this class if it is to work properly with the public class method search.
> Added search_joins to NetSuite::Records::Contact

- lib/netsuite/version.rb
- netsuite.gemspec
It was under `Netsuite` instead of `NetSuite` (capitalization) like
everything else in the gem. With this change there are no remaining references to `Netsuite`.
I noticed this while working on an application that kept its own NetSuite integration code under `Netsuite` to avoid collisions.
> Fix VERSION constant module

- lib/netsuite/errors.rb
Changes viewing errors in honeybadger from
`"#<NetSuite::Error:0x0055a605e61e90>"`
to
`"ERROR USER_ERROR You cannot edit the end of group line.  You must
delete the group."`
Which is helpful for debugging
Fixes: #343
> Allow errors to be represented as strings

- lib/netsuite/records/sales_order_item.rb
- spec/netsuite/records/sales_order_item_spec.rb
It's a boolean field, as per [the docs](http://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2016_1/schema/other/salesorderitem.html?mode=package).
> Support expand_item_group on SalesOrderItem records

- lib/netsuite/records/sales_order_item.rb
- spec/netsuite/records/sales_order_item_spec.rb
The quantity_committed had a typo on sales order item and other quantities were omitted.
> Add missing fields to sales order item

- lib/netsuite/records/support_case.rb
As far as I've been able to test. Adding the search action to the Support Case record works fine with out any further modification needed.
> add search to support case

- README.md
As discussed on Slack -- adding an example for this type of SO search that shows how to use the  `TransactionStatus._salesOrderPendingApproval` value for the `status` field.
More valid values are available in the Schema browser: https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2016_2/schema/enum/transactionstatus.html
I'm not sure about just pasting the Schema browser URL in a comment like that. Perhaps I should just remove that line.
> Add a SalesOrder search example for "Pending Approval" SO's.

- lib/netsuite/actions/search.rb
- lib/netsuite/support/search_result.rb
Performing a search action against a record class did not carry the explicitly passed credentials, which made the first page request and the following to have different authentication data.
> Fix multipage search not passing credentials

- lib/netsuite/support/country.rb
Use just `_libya` instead of `_libyanArabJamahiriya`
I discovered that one while syncing a Customer record with an address in Libya.
[Docs](https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_2/schema/enum/country.html?mode=package) for the enum value.
> Fix Libya's NetSuite country value

- lib/netsuite/records/custom_record_ref.rb
`internal_id` worked when using `CustomRecordRef` but if you wanted to reference another record using an `external_id` it did not set the attribute.  The `type_id` would get set but upsert would fail with `reference key null` error.
> Set external_id on custom_record_ref.rb to allow referencing

- lib/netsuite/support/country.rb
Use just `_samoa` instead of `_westernSamoa`
Very similar to the problem that #379 solved for Libya.
Linking the [docs](https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_2/schema/enum/country.html?mode=package) for the enum values for reference.
> Fix Samoa's NetSuite country value

- lib/netsuite/support/country.rb
This might be a little overwhelming to review. I removed this duplicated country code causing a constant override warning:
> `lib/netsuite/support/country.rb:187: warning: key "RS" is duplicated and overwritten on line 198`
> Remove duplicated Serbian country code

- lib/netsuite.rb
- lib/netsuite/records/entity_custom_field.rb
- spec/netsuite/records/basic_record_spec.rb
- spec/netsuite/records/entity_custom_field_spec.rb
This commit adds support for the [EntityCustomField](https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_1/schema/record/entitycustomfield.html) record.
> Add NetSuite::Records::EntityCustomField

- lib/netsuite.rb
- lib/netsuite/records/transaction_body_custom_field.rb
- spec/netsuite/records/basic_record_spec.rb
- spec/netsuite/records/transaction_body_custom_field_spec.rb
This commit adds support for [TransactionBodyCustomField](https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_1/schema/record/transactionbodycustomfield.html) record.
> Add NetSuite::Records::TransactionBodyCustomField

- lib/netsuite/actions/update.rb
Correct me if I am wrong, but I think that `#update` method shouldn't overwrite `external_id` if it is provided in `options`.
Currently, if we want to update `external_id` we have to do something like that:
```
customer.external_id = new_external_id # <= I do not think this should be needed
customer.update(attributes)
```
even when we have `externa_id` set in `attributes` because of [this line](https://github.com/NetSweet/netsuite/blob/70ab07710387ce32f746a6213ec1087a0f764ae7/lib/netsuite/actions/update.rb#L75).
This PR changes that, so update method will correctly update `external_id` if it is provided in attributes. Additionally I changed `#merge!` calls to `#[]=` since it is faster and should be preferred in my opinion ([rubocop …
> Do not overwrite 'external_id' attr in update

- lib/netsuite.rb
- lib/netsuite/records/bin_number.rb
- lib/netsuite/records/bin_number_list.rb
- spec/netsuite/records/bin_number_spec.rb
With this change we'll make sure we're using the right namespace for bin numbers, according to the netsuite schema documentation, both `BinNumberList` and `BinNumber` are defined under the `listAcct` namespace.
We'll also extract the `BinNumber` class into its own file and define the proper fields for it.
My app is using `2017_2` as its API version I'm not 100% sure if these changes are applicable to previous versions, I used the following link for reference: http://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2017_2/schema/other/inventoryitembinnumberlist.html?mode=package
> Fix bin number serialization

- lib/netsuite/actions/login.rb
Application ID needed for login call using 2015.2 endpoint.  Not sure if this is widespread, most people probably don't use this action.  But this will add the `application_id` if it's passed in the credentials hash.
```
D, [2019-04-17T20:00:54.845169 #9369] DEBUG -- : HTTPI /peer GET request to [ACCOUNT_ID]-sb1.suitetalk.api.netsuite.com (net_http)
I, [2019-04-17T20:00:55.301247 #9369]  INFO -- : SOAP request: https://webservices.netsuite.com/services/NetSuitePort_2015_2
I, [2019-04-17T20:00:55.302039 #9369]  INFO -- : SOAPAction: "login", Content-Type: text/xml;charset=UTF-8, Content-Length: 2035
D, [2019-04-17T20:00:55.303663 #9369] DEBUG -- : <?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" …
```
> Add application_id to soap_header if passed in login credentials

- lib/netsuite/support/search_result.rb
- spec/netsuite/support/search_result_spec.rb
`searchMoreWithId` operation is used for obtaining paged search results. But there is a case when it returns an empty "page" and it leads to an exception:
```
Traceback (most recent call last):
12: from script/rails:6:in `<main>'
11: from script/rails:6:in `require'
10: from /var/www/sites/shiphawk/shared/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
9: from /var/www/sites/shiphawk/shared/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
8: from /var/www/sites/shiphawk/shared/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:68:in `console'
7: from /var/www/sites/shiphawk/shared/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/console.rb:9:in `start'
6: from …
```
> Fix issue with empty `record_list` node in search result

- lib/netsuite/records/non_inventory_sale_item.rb
- spec/netsuite/records/non_inventory_sale_item_spec.rb
Direct revenue posting is a boolean for non-inventory sale item that you can find here http://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2018_2/schema/record/noninventorysaleitem.html
> Add direct_revenue_posting field to non-inventory sale item model

- README.md
The method name in the README for getting the data center URL seems to be incorrect. This should update it to the working method name with the results of the before and after commands shown below:
```
NetSuite::Utilities.netsuite_data_center_urls('TSTDRV1576318')
NoMethodError: undefined method `netsuite_data_center_urls' for NetSuite::Utilities:Module
```
```
NetSuite::Utilities.data_center_url('TSTDRV1576318')
=> "https://tstdrv1576318.suitetalk.api.netsuite.com"
```
Seems like this might be looked at because of an rspec screenshot:
> Update data center url method name in README

- lib/netsuite/records/item_fulfillment.rb
Item Fulfillments in NetSuite have a `status` field that should be available via the record.
> Add the status field to ItemFulfillments

- lib/netsuite/records/classification.rb
- spec/netsuite/records/classification_spec.rb
This was done to keep Classification consistent with Location and Department segments.
Fixes https://github.com/NetSweet/netsuite/issues/447
> update classification segment to include parent record_ref

- lib/netsuite/records/non_inventory_resale_item.rb
- spec/netsuite/records/non_inventory_resale_item_spec.rb
This adds the ability to add a Item Vendor List to a Non Inventory Resale Item.
It's a simple one line change.
I also added tests for Non Inventory Resale Item
> Add item vendor list to non inventory resale item

- lib/netsuite/records/invoice.rb
The Invoice object has an amount property in netsuite that can be
returned in transaction searches.  It should be available here too.
> Add amount as a read_only_field to Invoice

- spec/netsuite/records/custom_field_list_spec.rb
* Specify the `NoMethodError` to keep RSpec happy and to ensure that
other bugs don't sneak by as a passing test
* Upgrade single instance of `should` syntax to `expect`
Before:
```bash
dl@phoenix:~/src/netsuite (master)
$ rspec spec/netsuite/records/custom_field_list_spec.rb
Randomized with seed 16607
..........WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<NoMethodError: undefined method `nonexisting_custom_field' for #<NetSuite::Records::CustomFieldList:0x00007fd9c39ac9b0>>. Instead consider …
```
> Fix deprecation warnings in custom_field_list_spec.rb

- README.md
- lib/netsuite/configuration.rb
- spec/netsuite/configuration_spec.rb
It’s surprising to not be able to, in a rails console, increase
the verbosity of the gem’s logging without needing to:
1. Tweak an ENV variable or otherwise change an initializer
2. Directly set `Configuration#attributes`
Aka, I would expect the following to work, but it does not.
```
app:staging> NetSuite::Configuration.log_level
=> :info
app:staging> NetSuite::Configuration.log_level = :debug
=> :debug
app:staging> NetSuite::Configuration.log_level
=> :info
```
Seems like the only way to increase the verbosity is to directly set
the appropriate attribute, which seems to be an internal data structure not intended
to be used by client code.
```
gravity:staging> NetSuite::Configuration.attributes[:log_level]
=> :info
gravity:staging> NetSuite::Configuration.attributes[:log_level] = :debug …
```
> Allow `NetSuite::Configuration#log_level` to be reset

- lib/netsuite.rb
- lib/netsuite/records/customer_payment.rb
- lib/netsuite/records/customer_payment_credit.rb
- lib/netsuite/records/customer_payment_credit_list.rb
- lib/netsuite/records/purchase_order.rb
- spec/netsuite/records/customer_payment_credit_list_spec.rb
Kinda confused because I didn't see this `Record` type, however, the following already existed in `customer_payment_spec.rb`:
```
describe '#credit_list' do
it 'can be set from attributes'
it 'can be set from a CustomerPaymentCreditList object'
end
```
> CustomerPaymentCreditList

- lib/netsuite/records/partner.rb
- spec/netsuite/records/partner_spec.rb
Thanks for this gem. I started my first integration with NetSuite and this was a huge time saver!
My integration touched on partners and I noticed the field list and record refs were outdated compared to the 2020.2 schema, so this should bring the gem inline with that schema.
> Update fields/record refs on partner record to match 2020.2 schema

- lib/netsuite/records/customer_deposit.rb
- lib/netsuite/records/customer_payment.rb
- spec/netsuite/records/customer_payment_spec.rb
NS exposes a `paymentOption` recordRef field on both the [CustomerPayment](https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2020_2/schema/record/customerpayment.html) and [CustomerDeposit](https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2020_2/schema/record/customerdeposit.html) records. This PR adds support for it.
I manually tested these changes with a console and was able to read/write to the field to a live NS instance. I also updated the CustomerPayment test to ensure this field covered.
Tests pass for me locally:
> Add payment_option to CustomerPayment and CustomerDeposit

- lib/netsuite/configuration.rb
- spec/netsuite/configuration_spec.rb
This is related to https://github.com/NetSweet/netsuite/pull/445, which I believe first raised this issue.
Recent versions of the NS WSDL contain an incorrect endpoint reference. This seems to have begun on version 2020_1. If you go to `https://<acount_id>.suitetalk.api.netsuite.com/wsdl/v2020_1_0/netsuite.wsdl` you can see at the very bottom:
When requests are made to this endpoint the following error is returned:
> In this account, you must use account-specific domains with this SOAP web services endpoint. You can use the SOAP getDataCenterUrls operation to obtain the correct domain. Or, go to Setup > Company > Company Information in the NetSuite UI. Your domains are listed on the Company URLs tab.
To fix, I added a configuration option to set the WSDL endpoint:
```ruby …
```
> Enable `endpoint` as a configuration option to bypass NS WSDL issues

- lib/netsuite/records/accounting_period.rb
- lib/netsuite/records/purchase_order.rb
- spec/netsuite/records/customer_payment_credit_list_spec.rb
Only way to get the `closed` attribute (which does not appear on a simple `get`) for an `AccountingPeriod` is to request it as a column as part of an Advanced Search. This makes that possible.
> Accounting period closed

- README.md
The `wsdl_domain` is just a domain/hostname, no protocol, however `endpoint` expects to include a protocol, so when you're buliding the `endpoint` from the `wsdl_domain`, you need to prefix it with a protocol.
#473 introduced the ability to set the `endpoint`.
> Include protocol in readme examples setting endpoint from wsdl_domain

- lib/netsuite/support/search_result.rb
- spec/netsuite/actions/search_spec.rb
- spec/support/fixtures/search/saved_search_joined_custom_customer.xml
If you performed an advanced search specifying which columns to return and included externalId, you wouldn't be able to get the external_id from the resulting record via the usual external_id method. This now matches how internal_id is extracted.
Prior to this, calls to external_id returned:
```
> record.external_id
=> {:@external_id=>"customer_1"}
```
Now, it returns:
```
> record.external_id
=> "customer_1"
```
This originally surfaced in #470 as part of a larger change, but we're exploring taking that in a different direction, so extracted this out to it's own PR.
> Properly extract external_id from advanced search results

- README.md
These newer API versions expect the field to be identified by its scriptId, not internalId.
> Update readme for including custom fields in search result columns for API 2013.2 and newer

- lib/netsuite.rb
- lib/netsuite/records/cost_category.rb
- spec/netsuite/records/cost_category_spec.rb
This is an accounting list, like Term.
I copied the get, add, delete specs from the Term spec, but it seems a little redundant to repeat these on each record. Maybe it'd be better to have an "action matcher", like the "field matcher", to assert the right actions were defined, not testing the implementation of those actions, leaving that to the action-specific specs?
> Add CostCategory record

- README.md
Attempt to document #483.
I wasn't sure how best to convey this given it affects consuming the search results, not performing the search itself. It should also be unsurprising that you'd access these search-only fields the same way you'd access regular or read-only fields.
Had we buried these search-only fields in custom fields, like #426 first attempted, then I'd find that more surprising and warranting clearer documentation.
> Explain search only fields in Readme

- lib/netsuite/records/assembly_unbuild.rb
- lib/netsuite/records/currency_rate.rb
- lib/netsuite/records/estimate.rb
- lib/netsuite/records/invoice.rb
- lib/netsuite/records/invoice_item.rb
- lib/netsuite/records/item_fulfillment_item.rb
- lib/netsuite/records/item_receipt_item.rb
- lib/netsuite/records/member_list.rb
- lib/netsuite/records/non_inventory_purchase_item.rb
- lib/netsuite/records/non_inventory_resale_item.rb
- lib/netsuite/records/non_inventory_sale_item.rb
- lib/netsuite/records/opportunity.rb
- lib/netsuite/records/phone_call.rb
- lib/netsuite/records/serialized_assembly_item.rb
- lib/netsuite/records/service_resale_item.rb
- lib/netsuite/records/service_sale_item.rb
- lib/netsuite/records/transfer_order_item.rb
- lib/netsuite/records/vendor.rb
- lib/netsuite/support/fields.rb
- spec/netsuite/support/fields_spec.rb
In adding the start of search_only_fields, a couple standard fields were mistakenly re-defined as search_only_fields, which ended up excluding. them when pushing data to NetSuite, under the guise they were search-only.
Now it's impossible to define the same field twice.
As a result, had to fix a number of occurrences of fields repeated between `fields` and another definition (ie `record_refs`, `read_only_fields`, `field`).
The only notable fix is on `Invoice`, where `bill_address` and `ship_address` were previously defined as `fields`, then got repeated as `search_only_fields`. In old APIs (<= 2014.1), these seemed to actually be fields, however in newer APIs (>= 2014.2), they no longer are. I'm erring on the side of newer APIs here, removing them as `fields` and leaving them as …
> Avoid repeating field definitions

- README.md
Couldn't figure out why .reload wasn't working, but it's because the method is called refresh, not reload.
> Updates README.md to reflect task.refresh, not task.reload

- netsuite.gemspec
Savon has released new versions that have fixed the bug that previously prevented us from upgrading beyond version 2.11.1. We now don't need that unnecessary restriction and can work with newer Savon versions including the latest of 2.12.1.
> Updating necessary Savon version

- HISTORY.md
- lib/netsuite/actions/add.rb
- spec/netsuite/actions/add_spec.rb
- spec/support/fixtures/add/add_file.xml
When calling `File#add`, the response XML sets a `type="file"` attribute
on the `baseRef` element, where "file" corresponds to the NetSuite
record. This then causes Nori (the XML parser used by Savon, the SOAP
client) to interpret that element as representing a base64 encoded file,
so it tries to get fancy about how it parses that element into a hash by
returning an instance of it's `StringIOFile` class:
https://github.com/savonrb/nori/blob/f59f8e18b0e53285c87d75a635058745e66b0bfb/lib/nori/xml_utility_node.rb#L131-L136
Either NetSuite's doing something non-standard with it's use of the
`type` attribute that Nori is trying to enforce, or Nori is
over-aggressive in trying to typecast to aid the developer.
The end result was that when we tried to extract the `internal_id` from
the response, …
> Fix "undefined method `[]' for #<Nori::StringIOFile>" when adding File

- HISTORY.md
- lib/netsuite/records/matrix_option_list.rb
- spec/netsuite/records/matrix_option_list_spec.rb
When creating a matrix child item, you pass the matrix options, but
without #to_record, the right XML wasn't generated.
> Implement MatrixOptionList#to_record

- HISTORY.md
- lib/netsuite/actions/search.rb
- spec/netsuite/actions/search_spec.rb
- spec/support/fixtures/search/basic_search_contact.xml
Given a criteria like:
```ruby
{
field: 'company',
operator: 'anyOf',
value: [
NetSuite::Records::RecordRef.new(external_id: "abc"),
NetSuite::Records::RecordRef.new(external_id: "xyz"),
],
}
```
The gem was never passing that external ID to NetSuite for the result,
so you'd get a `INVALID_KEY_OR_REF` error as the XML line ended up
looking like:
```xml
<platformCore:searchValue xsi:type="platformCore:RecordRef" type="account"/>
```
Compared to the same line if you defined your `RecordRef` with an
internal ID:
```xml
<platformCore:searchValue internalId="1" xsi:type="platformCore:RecordRef" type="account"/>
```
Now that we pass the external ID too, that same line looks like:
```xml
<platformCore:searchValue externalId="abc" xsi:type="platformCore:RecordRef" type="account"/>
```
If your …
> Consider externalId in search criteria when using RecordRef as value

- HISTORY.md
- README.md
- lib/netsuite.rb
- lib/netsuite/records/credit_memo.rb
- lib/netsuite/records/invoice.rb
- lib/netsuite/records/null_field_list.rb
- lib/netsuite/support/records.rb
- spec/netsuite/records/credit_memo_spec.rb
- spec/netsuite/records/invoice_spec.rb
- spec/netsuite/records/null_field_list_spec.rb
- spec/netsuite/support/records_spec.rb
NullFieldList is used to either clear an existing value on update, or
avoid a default being applied on adding a record.
My use case only required support for credit memos and invoices, so I
started there, but this could likely be added to most records.
This was heavily inspired by @gmike11's work in #481, but that seems to
lump a bunch of changes together. This also solves #398.
Where #481 manipulated the XML request body to address that the
`<platformCore:nullFieldList>` needs to always use the `platformCore`
namespace, as opposed to the record's normal namespace (ie `transSale`
for invoice) as happens for any other field, I tried to address that on
the `#to_record` side.
> Add support for NullFieldList (starting with credit memos and invoices)

- HISTORY.md
- README.md
- lib/netsuite/records/assembly_item.rb
- lib/netsuite/records/description_item.rb
- lib/netsuite/records/discount_item.rb
- lib/netsuite/records/inventory_item.rb
- lib/netsuite/records/item_group.rb
- lib/netsuite/records/kit_item.rb
- lib/netsuite/records/lot_numbered_assembly_item.rb
- lib/netsuite/records/lot_numbered_inventory_item.rb
- lib/netsuite/records/non_inventory_purchase_item.rb
- lib/netsuite/records/non_inventory_resale_item.rb
- lib/netsuite/records/non_inventory_sale_item.rb
- lib/netsuite/records/other_charge_sale_item.rb
- lib/netsuite/records/payment_item.rb
- lib/netsuite/records/serialized_assembly_item.rb
- lib/netsuite/records/serialized_inventory_item.rb
- lib/netsuite/records/service_resale_item.rb
- lib/netsuite/records/service_sale_item.rb
- lib/netsuite/records/subtotal_item.rb
I also added some documentation about how to use the action.
The documentation reveals a few rough parts around this action. Notably:
The response you get back is very raw, and not a typical record. Given
how little data is returned, I'm not sure if it'd be better to
instantiate a full record for consistency, or if there should be a
new `DeletedRecord`-style record, with a field for `deleted_date`
and a record_ref for `record`, making it a little easier to work with.
You have to paginate yourself. Eventually it'd be nice if something like
`SearchResult#results_in_batches` were offered to do it for you, though
that'd be a breaking change to the return value of the action currently.
The record class you call `get_deleted` on has no influence on the
request actually performed, so without any …
> Add `get_deleted` action to item records

- lib/netsuite.rb
- lib/netsuite/actions/delete.rb
- lib/netsuite/actions/delete_list.rb
- lib/netsuite/actions/get.rb
- lib/netsuite/actions/get_deleted.rb
- lib/netsuite/actions/get_list.rb
- lib/netsuite/actions/initialize.rb
- lib/netsuite/actions/search.rb
- lib/netsuite/core_ext/string/lower_camelcase.rb
- lib/netsuite/records/record_ref.rb
- lib/netsuite/support/records.rb
- lib/netsuite/support/sublist.rb
- lib/netsuite/utilities/strings.rb
Our company enforces that we do not depend on gems that monkey patch core Ruby classes. To enable us to depend on this gem, this change moves the `lower_camelcase` to be a static method on a new utility class `NetSuite::Utilities::Strings`.
There are many places where `lower_camelcase` is used to generate a `record_type` so this change consolidates the logic in `NetSuite::Support::Records` and uses it where a record type is expected.
> Remove monkey patched `lower_camelcase` method on String

- lib/netsuite/records/item_availability.rb
- spec/netsuite/records/item_availability_spec.rb
- spec/support/fixtures/get_item_availability/get_item_availability.xml
Add get_item_availability operation that fetches ItemAvailability records for a list of InventoryItem refs.
https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_N3498308.html
Is NetSuite::Records::ItemAvailability class the right place for this operation? Or should it go to Actions?
> Add get_item_availability operation

- HISTORY.md
- lib/netsuite/actions/delete.rb
- spec/netsuite/actions/delete_spec.rb
- spec/support/fixtures/delete/delete_customer_error.xml
- spec/support/fixtures/delete/delete_customer_multiple_errors.xml
If the `delete` action returned false due to a NetSuite error, there
wasn't a way to access those errors. Now you can call `errors` on the
instance you tried deleting to access them, just like when adding,
updating, etc. instances.
> Expose `errors` after calls to `delete` action

- lib/netsuite/configuration.rb
- spec/netsuite/configuration_spec.rb
This change adds an optional `proxy` attribute on the `NetSuite::Configuration` that is passed to the generated Savon client used for requests to NetSuite.
> Add optional proxy for NetSuite requests through Savon

- lib/netsuite/actions/add.rb
- spec/netsuite/actions/add_spec.rb
- spec/support/fixtures/add/add_invoice.xml
Addresses issue [#444](https://github.com/NetSweet/netsuite/issues/444), where some successful requests return an empty error object.
See https://system.netsuite.com/help/helpcenter/en_US/WSDiff/2018_2/FolderComparisonReport_files/FileComparisonReport24.html, line 914 for the change to the platformCore schema, https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_4407992281.html for a description of afterSubmit scripts, and https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_N3536574.html#bridgehead_1515748728 for a discussion of error reporting for these scripts.
Also adds a line for File requests in the add action spec b/c the existing fixture already includes the `after_submit_failed` field.
Co-authored-by: Lily Burtness …
> Ignore status detail of after_submit_failed in error handling

- lib/netsuite/configuration.rb
- lib/netsuite/utilities.rb
- spec/netsuite/configuration_spec.rb
Making gem thread safe by wrapping instance variables in `Thread.current`. All tests are passing.
> Making gem thread safe

- netsuite.gemspec
Making a request with the NetSuite gem and Savon 2.13.0 caused the following error:
```
<faultstring>org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 435; The prefix "xmlns" cannot be bound to any namespace explicitly; neither can the namespace for "xmlns" be bound to any prefix explicitly.
```
Therefore, this PR locks the Savon gem to the last versions that work.
If I had to guess at the PR that caused the issue, I would suggest it is [this](https://github.com/savonrb/savon/pull/943) one.
> Locking Savon to < 2.13 to prevent an error making queries

- HISTORY.md
- README.md
- lib/netsuite/configuration.rb
- lib/netsuite/utilities.rb
- spec/netsuite/configuration_spec.rb
This is a follow up to #549 to improve usage in a single tenant scenario where you might configure NetSuite on the main thread (ie. via Rails initializer), then make requests in another thread (ie. Sidekiq jobs).
By default we assume single-tenant usage and the configuration is shared across all threads. If you opt into multi-tenant usage, each child thread starts with the main thread's configuration, but can then be further configured without altering other threads.
Rather than mixing `Thread.current` and global instance variables, I'm using `Thread.main` for the global configuration.
Child threads start with a copy of the main thread's attributes, figuring this still allows you to set some things globally on the main thread (ie. timeouts), then per-tenant things on the child threads …
> Add `Configuration#multi_tenant!` for opting into multi-tentant support where configuration is per-thread

- Gemfile
- HISTORY.md
- netsuite.gemspec
This version of Savon mistakenly prefixed the default namespace of `xmlns`, resulting in a namespace of `xmlns:xmlns`, which caused NetSuite to error on requests. v2.13.1 fixed this issue to skip prefixing the default namespace.
This is a continuation of #558, which avoided v2.13.0 and anything greater.
Bug: https://github.com/savonrb/savon/pull/943#issuecomment-1213163418
Fix: https://github.com/savonrb/savon/pull/977
> Avoid Savon version `2.13.0` to prevent generating invalid envelopes

- HISTORY.md
I noted the change to the default API version as a breaking change, as it could be if someone wasn't setting an `api_version` explicitly, relying on the default being `2015_1`, and doing something that might not be compatible with `2016_2`, though based on #554, it sounds like NetSuite isn't even supporting `2015_1` anymore, so the requests were probably failing already.
> Update HISTORY.md for v0.9.1 release [ci skip]

- lib/netsuite/records/invoice.rb
- spec/netsuite/records/invoice_spec.rb
Per the NetSuite schema browser the Invoice shipping_tax_code should be a record_ref, since at least API version 2014_1.
> Invoice shipping_tax_code should be a record_ref

- lib/netsuite/support/search_result.rb
- spec/netsuite/support/search_result_spec.rb
The client should just yield the blank page returned instead of crashing, but to ever receive this seems like a bug in suitetalk since we're using results_in_batches but on the final page sometimes a successful result is returned with no rows, probably because the underlying data no longer matches the search since our pagination takes an hour or so and we're running it across day boundaries, but you'd think search_id would represent an isolated view of the data we're paginating.  we haven't captured the log to see if total_records changes, but obviously total_pages doesn't since it successfully accepts page_index but just doesn't return any rows.
> dont crash if suitetalk returns empty <platformCore:searchRowList/>

- lib/netsuite/records/vendor_return_authorization.rb
- lib/netsuite/records/vendor_return_authorization_item.rb
Add :klass field to record VendorReturnAuthorization and VendorReturnAuthorizationItem
NoMethodError: undefined method `klass=' for #<NetSuite::Records::VendorReturnAuthorizationItem:0x00007fb216d14de8 @attributes={:item=>#<NetSuite::Records::RecordRef:0x00007fb216d1be90 @internal_id="555", @external_id=nil, @type=nil, @attributes={:name=>"0901JKE"}>, :line=>"2", :quantity=>"15.0", :description=>"", :rate=>"0.00", :amount=>"0.0", :location=>#<NetSuite::Records::RecordRef:0x00007fb216d1ba58 @internal_id="63", @external_id=nil, @type=nil, @attributes={:name=>""}>, :is_billable=>false, :is_closed=>false, :is_drop_shipment=>false}>
> Add :klass field to record VendorReturnAuthorizationItem & VendorReturnAuthorization

- HISTORY.md
- lib/netsuite/configuration.rb
- spec/netsuite/configuration_spec.rb
Savon will call `to_s` on any `proxy` value passed in so it will treat `nil` like an empty string instead of not using it. This causes requests to fail with an invalid proxy. This change will not pass in a value for `proxy` if the attribute is `nil`.
This change also updates history with addition of the proxy attribute.
A [fix was added to version 2.12.0 of savon](https://github.com/savonrb/savon/blob/master/CHANGELOG.md#2120-2018-01-16) but this changes allows netsuite to be compatible with earlier versions of savon.
> Optionally pass in `proxy` parameter to Savon

- lib/netsuite/records/invoice_item.rb
- spec/netsuite/records/invoice_item_spec.rb
There was a requirement from our consumer to add a createWo field in the inventory item.
While debugging further, it has been observed that create_wo is not part of the supported field list.
- Added create_wo field in Inventory Item
- Added field in specs to verify the presence of field
> Added create_wo field item in Invoice Item

- lib/netsuite/records/transfer_order.rb
- lib/netsuite/records/transfer_order_item.rb
An error occured while making:
- `get` on a Transfer Order
- modify the Transfer Order
- `upsert` the Transfer Order
- `shipping_address` has to be an `Address` in `transfer_order`
- `klass` has to be be a `record_ref` in `transfer_order_item`
> Fix fields definition for Transfer Orders

- lib/netsuite/records/purchase_order.rb
Per the NetSuite schema browser the Purchase Order shipping_to should be a record_ref, since at least API version 2014_1.
> Purchase Order ship_to should be a record_ref

- lib/netsuite/configuration.rb
- spec/netsuite/configuration_spec.rb
> The default timeout for reading from netsuite in the gem's configuration is 60 seconds, and the 'open' timeout can be set, but the 'write' timeout was not settable, and defaulted to [0.25 seconds](https://www.rubydoc.info/github/httprb/http/HTTP/Timeout/PerOperation).
> 
> Allow the write-timeout to be configured, and supply it to Savoy alongside the read and open timeouts.
(revert-revert from #587)
But this time, include a version-check - if Savon is below version 2.13.0, it doesn't accept `write_timeout`, and we should also complain (`NetSuite::ConfigurationError` if someone tries to set that option on _this_ gem). And I enabled CI on my fork, instead of running tests locally - I hadn't realized how much of a matrix you were testing against, sorry about that!
The …
> Add write timeout configuration (backwards compatible)

- lib/netsuite/records/cash_refund_item.rb
- spec/netsuite/records/cash_refund_item_spec.rb
Add 2 missing recordRefs to CashRefundItem class.
https://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2020_1/schema/other/cashrefunditem.html?mode=package
> Add department and location to CashRefundItem/record_refs

- lib/netsuite/records/inventory_assignment.rb
- spec/netsuite/records/inventory_assignment_spec.rb
The `inventoryStatus` field under of the `InventoryAssignment` is currently unsupported by the gem.
This should be added to support NetSuite accounts using Inventory Status in the inventory detail subrecord
> Add support to Inventory Status field

- lib/netsuite/records/customer_deposit.rb
`:klass` is included under fields. This doesn't allow us to correctly reference the record reference of the Class records in NetSuite.
> Customer Deposit - Move klass from fields to record_refs
